{'SF':'San Francisco',
'AQ':'air qualiy',
'AQI':'Air Quality Index',
'PG&E':'Pacific Gas and Electricity',
'Cal':'California',
'CA':'California',
'Ca':'California',
'Cali':'California',
'NorCal':'Northern California',
'Thx':'Thanks',
'hr':'hour',
'bc':'because',
'+':'and',
'gov':'government',
'Gov':'government',
'V. good':'Very good',}
